[package]
name = "nawah-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
nawah-core = { path = "../nawah-core" }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
bollard = "0.19.4"
futures-util = "0.3.31"
clap = { version = "4.5.51" , features = ["derive"] }
anyhow = "1.0.100"